services:
  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=movie-db
    ports:
      - "3307:3306"
    networks:
      - movie
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - movie

volumes:
  mysql-data:

networks:
  movie:
    driver: bridge
